# overall
PROVIDER=postgres
export COMPOSE_PROJECT_NAME=
#server
APP_PORT=
# postgres
POSTGRES_HOST_LOCAL=localhost
POSTGRES_USER=
POSTGRES_PASSWORD=
POSTGRES_DB=
POSTGRES_PORT=5432
# mssql
MSSQL_HOST_LOCAL=localhost
MSSQL_USER=test
MSSQL_PASSWORD=
MSSQL_DB=
MSSQL_PORT=1433
# azure
AZURE_HOST_LOCAL=<servername>.database.windows.net
AZURE_USER=
AZURE_PASSWORD=
AZURE_DB=
AZURE_PORT=1433
# redis
REDIS_PORT=6379
REDIS_SERVICE=redis
REDIS_CACHE_DISABLE=false