version: "3.5"

volumes:
  redis: {} # or :ro ; :rw

networks:
  rustnet:

services:

  redis:
    image: 'redis:3.2-alpine'
    ports: 
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - 'redis:/data'
    networks:
      - ${COMPOSE_PROJECT_NAME}net
  
  rust.server.prod.gcloud:
    # image: ${COMPOSE_PROJECT_NAME}.server:alpine
    # image is different from service because gcloud doesn't use build step
    image: ${COMPOSE_PROJECT_NAME}.server.prod.gcloud:ubuntu
    depends_on:
      - redis
    build:
      context: ../
      # dockerfile: docker/server/Dockerfile.server.alpine
      dockerfile: docker/server-prod/Dockerfile.server.ubuntu
    tty: true
    stdin_open: true
    working_dir: /usr/src/app
    env_file:
      - ".env"
    ports:
      - 5000:5000
    volumes:
      - ../server:/usr/src/app
      - /usr/src/app/node_modules
    command: ["docker-entrypoint-server-u.sh", "yarn", "run", "start"]
      # entrypoint: /usr/local/bin/docker-entrypoint-server-a.sh
    networks:
      - ${COMPOSE_PROJECT_NAME}net
    